apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: myapp
  namespace: test
spec:
  container:
    - name: nginx-container
      image: nginx:latest
      ports:
        - name: nginx-port
          containerPort: 80