apiVersion: v1
kind: Service
metadata:
  name: ciservice
  labels: 
    app: myapp
specs:
  type: ClusterIP
  selector:
    app: myapp
  ports:
    - name: nginxsvc-port
      protocol: TCP
      port: 80
      targetPort: 80
